### ISSUE TITLE
Consider renaming root element and change definition

### ISSUE THREAD

**Issue by rkottmann** [CenPC434/cius-extension-xml#11]
Currently, the root element is named `config` and has attribute with name `type` and either `cius` or `extension` as allowed values.

We think it would be better to have a root element with a more human readbale full spelling  e.g. `configurations` which has one  or many child elements being either `cius` or `extension` .

This would have the advantage that -- the yet to be determined way of describing an extension -- can significantly vary from our current defintion of a cius without any impact. Making the current XML model more future proof and easier to change.

**Comment by kosek** [comment]
I don't see need for storing multiple CIUSes/extensions in a single file. However I'm fine with changing root element name from `config` to `cius` and removing `type` attribute. For extensions we will introduce second possible root element `extension` once we will start working on extensions definition format. 

Would this work for you?

**Comment by rkottmann** [comment]
In many analysis scenarios it is easier to have all CIUSes or extensions in one XML for easier processing with e.g. XSLT. And if one sets element `cius` and `extension` to zero or many, but at least one of both has to occur, then people can create XML instances with just a single `cius` or just a single `extension`, and it also allows the possibility to create single file "databases" of them. Having both use cases with one solution rather then only one use case still sounds better to me.

**Comment by phax** [comment]
From an XSLT point of view it does not make a big difference to query `//config[@type='cius']` or `//cius` (at least imho).
The more fascinating query is indeed, if `cius` and `extension` will have the same element set or not....
I think that `extension` would get more elements on the constraint level????

**Comment by kosek** [comment]
> From an XSLT point of view it does not make a big difference to query //config[@type='cius'] or //cius (at least imho).
The more fascinating query is indeed, if cius and extension will have the same element set or not....
I think that extension would get more elements on the constraint level????

The truth is that due to limitations of XSD it would be easier to have different content models for extensions and CIUSes if different elements are used. As we don't know yet which additional elements will be needed for describing extensions it's safer to use different elements.

> In many analysis scenarios it is easier to have all CIUSes or extensions in one XML for easier processing with e.g. XSLT. And if one sets element cius and extension to zero or many, but at least one of both has to occur, then people can create XML instances with just a single cius or just a single extension, and it also allows the possibility to create single file "databases" of them. Having both use cases with one solution rather then only one use case still sounds better to me.

We should keep things simple. Standard we are developing is targeted at describing **one** CIUS. If needed anyone can put more CIUSes into a single file without having standard for it. That's flexibility of XML.
