### ISSUE TITLE
Move description element to meta section

### ISSUE THREAD

**Issue by larsroelkerdenker** [CenPC434/cius-extension-xml#8]
KoSIT proposes to move the description element into meta data section above.

Reason: A human readable description is in our understanding part of a meta data section.

**Comment by kosek** [comment]
Please note that human readable description can be very long - it can be formatted text having several pages in length, e.g. see Italian CIUS at https://www.agid.gov.it/sites/default/files/repository_files/documentazione/eigor_cius_it_rel_1_0_0_accessibile_0.pdf

In my opinion such long description is no longer metadata, it's core of information that is being described by metadata. Currently meta element contains important metadata about CIUS including brief textual description in the abstract element.

**Comment by rkottmann** [comment]
Now, I better understand the purpouse of this element. Our German CIUS document is also quiet long and we **do not** have an HTML version of it, but PDF. For the reason of being long and in various formats, I'd suggest to make the description element a URL (and I really mean web reachable resource locator) to such a document in whatever format. 

And if you agree to this it would make sense again, to add it to the meta data section. Otherwise, I would like to suggest to make it an optional element.

**Comment by kosek** [comment]
For linking to existing external specification you can use `link` element in metadata section. We should keep `description` element for those who would like to put verbose content directly into XML and generate human readable version from this. You are right that such element should be optional as many real world CIUSes don't need it -- they will be just fine with metadata and rules.
